### ISSUE TITLE
[NumberGuesser] Ругательства

### ISSUE THREAD

**Issue by pavel-b-novikov** [ksushanam/nsudotnet#3]
Имя игрока должно вшиваться в ругательство, а не припечатываться к нему с боку

**Comment by ksushanam** [comment]
исправила

**Comment by pavel-b-novikov** [comment]
Всё еще припечатывается сбоку. С левого.

**Comment by ksushanam** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
и так сойдет
