### ISSUE TITLE
[TicTacToe] Архитектура

### ISSUE THREAD

**Issue by pavel-b-novikov** [ksushanam/nsudotnet#5]
Итак, у вас есть ConsoleGameWriter и GameModel. Объясните мне с какого банана половину работы по выведению поля на экран (при том ещё и используя Console напрямую) выполняет GameModel? 
Смысл этого задания в том. чтобы вы сделали такую систему абстракций, которую потом без изменений можно будет использовать в WPF или каком-либо другом графическом приложении. У вас же криво разнесены обязанности. Правьте.

**Comment by ksushanam** [comment]
исправила, теперь все в ConsoleGameWriter
