### ISSUE TITLE
[TicTacToe] Issue специально для Анатолия Баранова

### ISSUE THREAD

**Issue by pavel-b-novikov** [ksushanam/nsudotnet#7]
Берите Ксюшину реализацию задачи, конвертируйте в Class Library, соберите в .dll. 
Затем откройте студию у себя, создайте Windows Forms-приложение и наговнякайте простенький фронтенд с 91-ю кнопочками (ради всего святого, используйте циклы), который просто пробрасывает клики в Ксюшину dll-ку, забирает оттуда состояние игры и отображает его. *Не надо* лепить сверх-красивый UI и сверх-крутой код - за это штрафовать не буду. Результат залейте на github.

Как буду проверять: заберу с github-а Ксюшину реализацию, соберу dll сам, подключу к вашему проекту. 

Правила: Игнорируя ваш предыдущий опыт, считайте что у вас обоих есть по 8 баллов.
За *каждое* изменение *Ксюшиных* исходников, выраженное в коммите в Ксюшин репозиторий и вы и Ксюша будете получать -1 балл.

Вперед.

**Comment by Tolya271** [comment]
Здравствуйте, получилось так, что я увидел ваше замечание, только когда уже хотел ответить вам, что всё готово, поэтому разница между коммитами составляет около 2 минут
Ссылка на репозиторий : https://github.com/Tolya271/nsudotnet

**Comment by pavel-b-novikov** [comment]
@Tolya271 подпишитесь на меня в гитхабе пожалуйста

**Comment by Tolya271** [comment]
Извините, забыл. Сделано.

**Comment by pavel-b-novikov** [comment]
Без временных ограничений задача теряет всякий смысл. Но черт с ним, все-таки сделали.
